/* Allegro datafile object indexes, produced by grabber v4.2.1, MinGW32 */
/* Datafile: c:\Users\prasanth\Desktop\rohan (3)\rohan\data.dat */
/* Date: Tue Oct 28 14:11:26 2014 */
/* Do not hand edit! */

#define back                             0        /* BMP  */
#define ball                             1        /* BMP  */
#define bulb                             2        /* BMP  */
#define bulbon                           3        /* BMP  */
#define but1                             4        /* BMP  */
#define carrierbot                       5        /* BMP  */
#define continu                          6        /* BMP  */
#define drill                            7        /* BMP  */
#define drill2                           8        /* BMP  */
#define drop1                            9        /* BMP  */
#define drop2                            10       /* BMP  */
#define drop3                            11       /* BMP  */
#define drop4                            12       /* BMP  */
#define electric                         13       /* BMP  */
#define end                              14       /* BMP  */
#define endon                            15       /* BMP  */
#define endon1                           16       /* BMP  */
#define endon2                           17       /* BMP  */
#define endon3                           18       /* BMP  */
#define fan                              19       /* BMP  */
#define fan2                             20       /* BMP  */
#define fanon1                           21       /* BMP  */
#define fanon2                           22       /* BMP  */
#define fanon3                           23       /* BMP  */
#define food                             24       /* BMP  */
#define foodlo                           25       /* BMP  */
#define gen                              26       /* BMP  */
#define genon1                           27       /* BMP  */
#define genon2                           28       /* BMP  */
#define genon3                           29       /* BMP  */
#define gomenu                           30       /* BMP  */
#define heater                           31       /* BMP  */
#define heatpower                        32       /* BMP  */
#define hon                              33       /* BMP  */
#define infbulb                          34       /* BMP  */
#define infend                           35       /* BMP  */
#define inffan                           36       /* BMP  */
#define infgen                           37       /* BMP  */
#define infkettle                        38       /* BMP  */
#define infmain                          39       /* BMP  */
#define infpuller                        40       /* BMP  */
#define infpusher                        41       /* BMP  */
#define infsolar                         42       /* BMP  */
#define infwall                          43       /* BMP  */
#define intro                            44       /* BMP  */
#define intro2                           45       /* BMP  */
#define kettle                           46       /* BMP  */
#define kettle2                          47       /* BMP  */
#define kon                              48       /* BMP  */
#define l11                              49       /* BMP  */
#define l12                              50       /* BMP  */
#define l13                              51       /* BMP  */
#define l14                              52       /* BMP  */
#define l15                              53       /* BMP  */
#define l16                              54       /* BMP  */
#define l17                              55       /* BMP  */
#define l18                              56       /* BMP  */
#define l21                              57       /* BMP  */
#define l31                              58       /* BMP  */
#define l41                              59       /* BMP  */
#define laser                            60       /* BMP  */
#define laser2                           61       /* BMP  */
#define laserre                          62       /* BMP  */
#define level11                          63       /* BMP  */
#define level22                          64       /* BMP  */
#define level33                          65       /* BMP  */
#define level44                          66       /* BMP  */
#define menumain                         67       /* BMP  */
#define mirdo                            68       /* BMP  */
#define mirdo2                           69       /* BMP  */
#define mirup                            70       /* BMP  */
#define mirup2                           71       /* BMP  */
#define music                            72       /* BMP  */
#define non                              73       /* BMP  */
#define off1                             74       /* BMP  */
#define off2                             75       /* BMP  */
#define on1                              76       /* BMP  */
#define on2                              77       /* BMP  */
#define play                             78       /* BMP  */
#define power                            79       /* BMP  */
#define powon                            80       /* BMP  */
#define pullbot                          81       /* BMP  */
#define pullbot2                         82       /* BMP  */
#define pushbot                          83       /* BMP  */
#define pushbot2                         84       /* BMP  */
#define restart                          85       /* BMP  */
#define shoot                            86       /* BMP  */
#define shoot2                           87       /* BMP  */
#define solar                            88       /* BMP  */
#define solon                            89       /* BMP  */
#define son                              90       /* BMP  */
#define spring                           91       /* BMP  */
#define spybot                           92       /* BMP  */
#define supply                           93       /* BMP  */
#define t1                               94       /* BMP  */
#define t2                               95       /* BMP  */
#define title                            96       /* BMP  */
#define ton                              97       /* BMP  */
#define truck                            98       /* BMP  */
#define truck2                           99       /* BMP  */
#define tut                              100      /* BMP  */
#define von                              101      /* BMP  */
#define wall                             102      /* BMP  */
#define wifir                            103      /* BMP  */
#define wifis                            104      /* BMP  */
#define wiree                            105      /* BMP  */
#define wireh                            106      /* BMP  */
#define wiren                            107      /* BMP  */
#define wires                            108      /* BMP  */
#define wiret                            109      /* BMP  */
#define wirev                            110      /* BMP  */
#define wirew                            111      /* BMP  */

